### ISSUE TITLE
W0640: why is the "problematic" code problematic?

### ISSUE THREAD

**Issue by bersbersbers** [vald-phoenix/pylint-errors#7]
> This will result in all closures using the same value for the closed-over variable.
```python
def foo(numbers):
    for i in numbers:
        def bar():
            print(i)
        bar()
```

Using the above code followed by `foo([1, 2, 3])` prints 
```
1
2
3
```
which I believe is expected. It seems all closures are *NOT* using the same value for the closed-over variable in this example.

**Comment by vald-phoenix** [comment]
Yea, indeed. This example was nicked from the official pylint test case maybe it's worth raising with them:
https://github.com/PyCQA/pylint/blob/main/tests/functional/n/nested_func_defined_in_loop.py

**Comment by bersbersbers** [comment]
Thanks, done!
